# Generated by Django 4.2.11 on 2024-04-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClassDepartamento', to='departamento.departamento')),
            ],
        ),
    ]
