# Generated by Django 4.2.11 on 2024-04-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ano', '0001_initial'),
        ('Turma', '0001_initial'),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resisto', models.DateField()),
                ('emis', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('naran', models.CharField(blank=True, max_length=50, null=True)),
                ('Data_moris', models.DateField()),
                ('Sexo', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=20, null=True)),
                ('naran_aman', models.CharField(blank=True, max_length=22, null=True)),
                ('naran_inan', models.CharField(blank=True, max_length=22, null=True)),
                ('nu_telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('religiaun', models.CharField(blank=True, max_length=50, null=True)),
                ('Osan_resistu', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('image', models.ImageField(null=True, upload_to='estudante/')),
                ('Ano_Resisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TinanR', to='Ano.ano', verbose_name='Ano')),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AdministrativePost', to='custom.administrativepost')),
                ('aldeia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipality', to='custom.municipality')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village', to='custom.village')),
            ],
        ),
        migrations.CreateModel(
            name='DetailEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_aprovadu', models.BooleanField(blank=True, default=False, null=True)),
                ('is_reprovadu', models.BooleanField(blank=True, default=False, null=True)),
                ('Ano_Academinco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TinanA', to='Ano.ano', verbose_name='Ano')),
                ('Turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turma.turma')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
    ]
