# Generated by Django 4.2.11 on 2024-05-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='Osan_resistu',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='religiaun',
        ),
    ]
