# Generated by Django 4.2.11 on 2024-05-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('estudante', '0002_remove_estudante_osan_resistu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='aldeia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='estudante/'),
        ),
    ]
