# Generated by Django 4.2.11 on 2024-05-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0003_alter_estudante_aldeia_alter_estudante_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='emis',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
