# Generated by Django 4.2.11 on 2024-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0004_alter_estudante_emis'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='have_classes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
