# Generated by Django 4.2.9 on 2024-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0006_estudante_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='naran_aman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='naran_inan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
