# Generated by Django 4.2.20 on 2025-08-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Turma", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estudante", "0007_alter_estudante_naran_aman_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[("IN", "Transfer In"), ("OUT", "Transfer Out")],
                        max_length=3,
                    ),
                ),
                (
                    "from_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("to_school", models.CharField(blank=True, max_length=100, null=True)),
                ("transfer_date", models.DateField()),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="estudante.estudante",
                    ),
                ),
                (
                    "from_turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_from",
                        to="Turma.turma",
                    ),
                ),
                (
                    "to_turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to",
                        to="Turma.turma",
                    ),
                ),
            ],
        ),
    ]
