# Generated by Django 4.2.20 on 2025-08-27 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Turma", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Ano", "0002_ano_is_active"),
        ("estudante", "0008_transferstudent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graduation_date", models.DateField()),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("graduation_remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "career_path",
                    models.CharField(
                        blank=True,
                        help_text="Current career or further studies",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True, help_text="Updated contact information", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_alumni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni_graduates",
                        to="Turma.turma",
                    ),
                ),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_records",
                        to="estudante.estudante",
                    ),
                ),
                (
                    "graduation_year",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni_graduates",
                        to="Ano.ano",
                    ),
                ),
            ],
        ),
    ]
