# Generated by Django 4.2.11 on 2024-04-20 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funsionariu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=200, null=True)),
                ('Sexo', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=20, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('nu_telefone', models.CharField(max_length=200, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('Permanente', 'Permanente'), ('Kontratadu', 'Kontratadu'), ('Voluntario', 'Voluntario')], max_length=20, null=True)),
                ('nivel_estudu', models.CharField(choices=[('Secundario', 'Secundario'), ('Diploma 1', 'Diploma 1'), ('Diploma 2', 'Diploma 2'), ('Diploma 3', 'Diploma 3'), ('Lisemsiatura', 'Lisensiatura'), ('Masterado', 'Masterado'), ('Doutoramento', 'Doutoramento')], max_length=20, null=True)),
                ('area_estudu', models.CharField(blank=True, max_length=50, null=True)),
                ('pozisaun', models.CharField(blank=True, max_length=50, null=True)),
                ('estadu_civil', models.CharField(blank=True, choices=[('Klosan', 'Klosan'), ('Kazadu', 'Kazadu'), ('Berlakiadu', 'Berlakeadu')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='funsionariu')),
                ('tipu_f', models.CharField(blank=True, choices=[('Dir', 'Diretor'), ('Fun', 'Funsionariu'), ('EIP', 'Ekipa Implementasaun Programa')], max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AAdministrativePost', to='custom.administrativepost')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MMunicipality', to='custom.municipality')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VVillage', to='custom.village')),
            ],
        ),
        migrations.CreateModel(
            name='UserFunsionariu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('funsionariu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funsionariu.funsionariu')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFunsionariu', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
