# Generated by Django 4.2.11 on 2024-06-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funsionariu',
            name='codeP',
            field=models.CharField(max_length=10, null=True, verbose_name='Codigu professores'),
        ),
    ]
