# Generated by Django 5.0.6 on 2024-06-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0002_funsionariu_codep'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepFun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funsionariu',
            name='tipu_f',
        ),
        migrations.AddField(
            model_name='funsionariu',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.depfun'),
        ),
    ]
