# Generated by Django 4.2.9 on 2024-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0003_depfun_remove_funsionariu_tipu_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funsionariu',
            name='nivel_estudu',
            field=models.CharField(choices=[('Secundario', 'Secundario'), ('Diploma 1', 'Diploma 1'), ('Diploma 2', 'Diploma 2'), ('Diploma 3', 'Diploma 3'), ('Lisensiatura', 'Lisensiatura'), ('Masterado', 'Masterado'), ('Doutoramento', 'Doutoramento'), ('Finalista', 'Finalista')], max_length=20, null=True),
        ),
    ]
