# Generated by Django 4.2.20 on 2025-03-29 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funsionariu', '0004_alter_funsionariu_nivel_estudu'),
    ]

    operations = [
        migrations.AddField(
            model_name='funsionariu',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFunsionarius', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='funsionariu',
            name='estadu_civil',
            field=models.CharField(blank=True, choices=[('Klosan', 'Klosan'), ('Kazadu', 'Kazadu'), ('Berlakiadu', 'Berlakeadu'), ('Relijiozu', 'Relijiozu')], max_length=20, null=True),
        ),
    ]
