# Generated by Django 4.2.20 on 2025-03-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turma', '0001_initial'),
        ('Ano', '0001_initial'),
        ('funsionariu', '0005_funsionariu_user_alter_funsionariu_estadu_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunsionarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnoFunTurma', to='Ano.ano')),
                ('funsionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Funsionario', to='funsionariu.funsionariu')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TurmaFun', to='Turma.turma')),
            ],
        ),
    ]
