# Generated by Django 4.2.20 on 2025-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funsionariu", "0006_funsionarioturma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funsionariu",
            name="codeP",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Codigu professores"
            ),
        ),
    ]
