# Generated by Django 4.2.20 on 2025-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funsionariu", "0007_alter_funsionariu_codep"),
    ]

    operations = [
        migrations.AddField(
            model_name="funsionariu",
            name="data_moris",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="funsionariu",
            name="fatin_moris",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="funsionariu",
            name="hela_fatin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
