# Generated by Django 4.2.20 on 2025-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funsionariu", "0008_funsionariu_data_moris_funsionariu_fatin_moris_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funsionariu",
            name="data_moris",
            field=models.DateField(blank=True, null=True),
        ),
    ]
