# Generated by Django 4.2.11 on 2024-04-20 05:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naran_eskola', models.CharField(max_length=50)),
                ('Motto', ckeditor_uploader.fields.RichTextUploadingField()),
                ('visaun', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Missaun', ckeditor_uploader.fields.RichTextUploadingField()),
                ('historia_eskola', ckeditor_uploader.fields.RichTextUploadingField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
