# Generated by Django 4.2.20 on 2025-04-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ano',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
