# Generated by Django 4.2.11 on 2024-04-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disiplina', '0001_initial'),
        ('funsionariu', '0001_initial'),
        ('Turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_est',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oras_hahu', models.TimeField(blank=True, max_length=20, null=True)),
                ('oras_remata', models.TimeField(blank=True, max_length=20, null=True)),
                ('loron', models.CharField(choices=[('Segunda', 'Segunda'), ('Tersa', 'Tersa'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sesta', 'Sesta'), ('Sabadu', 'Sabadu'), ('Domingo', 'Domingo')], max_length=20, null=True)),
                ('Diciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disiplina.diciplina')),
                ('profesores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsionariu.funsionariu')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Turma.turma')),
            ],
        ),
    ]
