# Generated by Django 4.2.11 on 2024-06-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_est',
            name='oras_hahu',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario_est',
            name='oras_remata',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
