# Generated by Django 4.2.6 on 2024-06-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_alter_horario_est_oras_hahu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oras_hahu', models.TimeField(blank=True, null=True)),
                ('oras_remata', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='horario_est',
            name='oras_hahu',
        ),
        migrations.RemoveField(
            model_name='horario_est',
            name='oras_remata',
        ),
        migrations.AddField(
            model_name='horario_est',
            name='Horas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.horas'),
        ),
    ]
