# Generated by Django 4.2.6 on 2024-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_horas_remove_horario_est_oras_hahu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_est',
            name='loron',
            field=models.CharField(choices=[('Day One', 'Day One'), ('Day Two', 'Day Two'), ('Day Three', 'Day Three'), ('Day Four', 'Day Four'), ('Day Five', 'Day Five')], max_length=20, null=True),
        ),
    ]
