# Generated by Django 4.2.20 on 2025-05-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_alter_horario_est_loron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_est',
            name='loron',
            field=models.CharField(choices=[('Segunda-Feira', 'Segunda-Feira'), ('Tersa-Feira', 'Tersa-Feira'), ('Kuarta-Feira', 'Kuarta-Feira'), ('Kinta-Feira', 'Kinta-Feira'), ('Sexta-Feira', 'Sexta-Feira'), ('Sabadu', 'Sabadu')], max_length=20, null=True),
        ),
    ]
