# Generated by Django 4.2.11 on 2024-04-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudante', '0001_initial'),
        ('Disiplina', '0001_initial'),
        ('Ano', '0001_initial'),
        ('Turma', '0001_initial'),
        ('Classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_periode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='valor_est',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_final', models.IntegerField()),
                ('por_extenso', models.CharField(max_length=32, null=True)),
                ('Diciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disiplina.diciplina')),
                ('Tinan_periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ano.ano')),
                ('Turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turma.turma')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valor.periode')),
            ],
        ),
        migrations.CreateModel(
            name='Clasificasao_valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificasao', models.IntegerField()),
                ('No_clasificasao', models.IntegerField()),
                ('Comportamento', models.TextField(max_length=100)),
                ('Aplicasao_assiduidade', models.TextField(max_length=100)),
                ('Higene', models.TextField(max_length=32, null=True)),
                ('Justificasao', models.IntegerField()),
                ('Injustificasao', models.IntegerField()),
                ('Klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classe.classe')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valor.periode')),
            ],
        ),
    ]
