# Generated by Django 4.2.6 on 2024-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valor_est',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
