# Generated by Django 4.2.20 on 2025-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor', '0002_valor_est_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
